# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NiCbRpqGl1Uz5LfHXgh4dwyt5tJL4m1-
"""

import numpy as np

import pandas as pd

import matplotlib.pyplot as plt

"""#Reading the data file"""

df=pd.read_csv("/content/housing.csv")

print(df)

"""#printing the shape"""

print(df.shape)

"""#printing top 10 and bottom 10 rows"""

print(df.head(10))

print(df.tail(10))



"""#printing the columns"""

print(df.columns)

"""#print a feature value"""

print(df['Price'])

"""# Selecting one input feature and target feature (dependent) for 150 rows only"""

X = df['Price'].head(150).values.reshape(-1,1)

y = df['Area Population'].head(150).values.reshape(-1, 1)

"""#visualizing these values"""

plt.scatter(X, y)

plt.title("Scatter Plot of Price vs. Area Population")

plt.show

"""#printing the statistical summary"""

print(df.describe())

